from app import db, Customer, Drinks, Orders, Bartender, Payment

db.drop_all()
db.create_all()

add_customer1 = Customer(name="Jeff Brown", is_old_enough=True)
add_bartender1 = Bartender(name="Peter Wilson", start_date="2018-01-31", position="Team Leader", rate_of_pay=9.40)
add_drinks1 = Drinks(beverage_name="Peroni", price=3.99, alcohol_percent=5.0, units_of_alcohol=1.7)
add_payment1 = Payment(payment_type="Debit Card", bank="Barclays", account_number=18231723, sort_code=128374, cvv=987)

add_customer2 = Customer(name="Terrance Lawless", is_old_enough=True)
add_bartender2 = Bartender(name="Vannessa Michaelson", start_date="2015-03-02", position="Bar Manager", rate_of_pay=12.00)
add_drinks2 = Drinks(beverage_name="Birra Morreti", price=3.49, alcohol_percent=4.5, units_of_alcohol=1.3)
add_payment2 = Payment(payment_type="Cash")

add_customer3 = Customer(name="George Smith", is_old_enough=True)
add_bartender3 = Bartender(name="Freddy Jenkins", start_date="2021-01-15", position="Bar Associate", rate_of_pay=9.00)
add_drinks3 = Drinks(beverage_name="Prosecco", price=11.49, alcohol_percent=12.1, units_of_alcohol=3.3)
add_payment3 = Payment(payment_type="Debit Card", bank="RBS", account_number=12278546, sort_code=715243, cvv=465)

add_customer4 = Customer(name="Margret Jones", is_old_enough=True)
add_bartender4 = Bartender(name="Arthur Davidson", start_date="2019-10-06", position="Bar Associate", rate_of_pay=9.00)
add_drinks4 = Drinks(beverage_name="Chardonnay", price=5.19, alcohol_percent=9.1, units_of_alcohol=1.8)
add_payment4 = Payment(payment_type="Debit Card", bank="Halifix", account_number=23417693, sort_code=162332, cvv=714)


db.session.add(add_customer1)
db.session.add(add_bartender1)
db.session.add(add_drinks1)
db.session.add(add_payment1)
db.session.add(add_customer2)
db.session.add(add_bartender2)
db.session.add(add_drinks2)
db.session.add(add_payment2)
db.session.add(add_customer3)
db.session.add(add_bartender3)
db.session.add(add_drinks3)
db.session.add(add_payment3)
db.session.add(add_customer4)
db.session.add(add_bartender4)
db.session.add(add_drinks4)
db.session.add(add_payment4)
db.session.commit()

add_order1 = Orders(quantity=1, order_cost=11.49, datetime_of_order="2021-03-10 15:13:30", customer_id=1, beverage_id=3, employee_id=4, payment_id=1)
add_order2 = Orders(quantity=2, order_cost=7.98, datetime_of_order="2021-03-10 15:20:14", customer_id=2, beverage_id=1, employee_id=3, payment_id=2)
add_order3 = Orders(quantity=2, order_cost=6.98, datetime_of_order="2021-03-10 15:25:54", customer_id=1, beverage_id=2, employee_id=4, payment_id=2)
add_order4 = Orders(quantity=1, order_cost=3.99, datetime_of_order="2021-03-10 15:27:24", customer_id=3, beverage_id=1, employee_id=1, payment_id=3)
add_order5 = Orders(quantity=2, order_cost=5.19, datetime_of_order="2021-03-10 15:31:43", customer_id=4, beverage_id=4, employee_id=3, payment_id=4)
add_order6 = Orders(quantity=2, order_cost=22.98, datetime_of_order="2021-03-10 15:38:39", customer_id=2, beverage_id=3, employee_id=2, payment_id=2)
add_order7 = Orders(quantity=4, order_cost=12.96, datetime_of_order="2021-03-10 15:45:57", customer_id=3, beverage_id=2, employee_id=4, payment_id=3)

db.session.add(add_order1)
db.session.add(add_order2)
db.session.add(add_order3)
db.session.add(add_order4)
db.session.add(add_order5)
db.session.add(add_order6)
db.session.add(add_order7)
db.session.commit()
